name: Run tests
on:
    push:
jobs:
    test:
        name: Test on ${{ matrix.os }}
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - name: Setup go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14.x
            - name: Check out code into the Go module directory
              uses: actions/checkout@v1
            - name: setup dependent modules
              run: go mod vendor
            - name: Test codek
              run: go test -v 
